// <auto-generated />
using System;
using Scheduler.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Scheduler.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230320031142_NewSchedulingColumns")]
    partial class NewSchedulingColumns
    {
/// <inheritdoc />
protected override void BuildTargetModel(ModelBuilder modelBuilder)
{
#pragma warning disable 612, 618
    modelBuilder
.HasAnnotation("ProductVersion", "7.0.3")
.HasAnnotation("Relational:MaxIdentifierLength", 128);

    SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

    modelBuilder.Entity("Scheduler.Models.Category", b =>
{
    b.Property<int>("Id")
.ValueGeneratedOnAdd()
.HasColumnType("int")
.HasColumnName("id");

    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

    b.Property<string>("Name")
.HasColumnType("nvarchar(max)")
.HasColumnName("name");

    b.Property<DateTime>("RegisterDate")
.HasColumnType("datetime2")
.HasColumnName("register_date");

    b.Property<int>("Status")
.HasColumnType("int")
.HasColumnName("status");

    b.Property<DateTime>("UpdateDate")
.HasColumnType("datetime2")
.HasColumnName("update_date");

    b.HasKey("Id");

    b.ToTable("categories");
});

    modelBuilder.Entity("Scheduler.Models.Company", b =>
{
    b.Property<int>("Id")
.ValueGeneratedOnAdd()
.HasColumnType("int")
.HasColumnName("id");

    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

    b.Property<string>("CNPJ")
.HasColumnType("nvarchar(max)")
.HasColumnName("cnpj");

    b.Property<string>("Description")
.IsRequired()
.HasColumnType("nvarchar(max)")
.HasColumnName("description");

    b.Property<string>("Image")
.HasColumnType("nvarchar(max)")
.HasColumnName("image");

    b.Property<string>("Name")
.IsRequired()
.HasColumnType("nvarchar(max)")
.HasColumnName("name");

    b.Property<DateTime>("RegisterDate")
.HasColumnType("datetime2")
.HasColumnName("register_date");

    b.Property<int>("Status")
.HasColumnType("int")
.HasColumnName("status");

    b.Property<DateTime>("UpdateDate")
.HasColumnType("datetime2")
.HasColumnName("update_date");

    b.HasKey("Id");

    b.ToTable("companies");
});

    modelBuilder.Entity("Scheduler.Models.CompanyOpeningHours", b =>
{
    b.Property<int>("Id")
.ValueGeneratedOnAdd()
.HasColumnType("int")
.HasColumnName("id");

    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

    b.Property<DateTime>("ClosingHour")
.HasColumnType("datetime2")
.HasColumnName("closing_hour");

    b.Property<int>("CompanyId")
.HasColumnType("int")
.HasColumnName("company_id");

    b.Property<int>("DayOfWeek")
.HasColumnType("int")
.HasColumnName("day_of_week");

    b.Property<DateTime>("OpeningHour")
.HasColumnType("datetime2")
.HasColumnName("opening_hour");

    b.Property<DateTime>("RegisterDate")
.HasColumnType("datetime2")
.HasColumnName("register_date");

    b.Property<int>("Status")
.HasColumnType("int")
.HasColumnName("status");

    b.Property<DateTime>("UpdateDate")
.HasColumnType("datetime2")
.HasColumnName("update_date");

    b.HasKey("Id");

    b.HasIndex("CompanyId");

    b.ToTable("company_opening_hours");
});

    modelBuilder.Entity("Scheduler.Models.CompanyOwners", b =>
{
    b.Property<int>("Id")
.ValueGeneratedOnAdd()
.HasColumnType("int")
.HasColumnName("id");

    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

    b.Property<int>("CompanyId")
.HasColumnType("int")
.HasColumnName("company_id");

    b.Property<DateTime>("RegisterDate")
.HasColumnType("datetime2")
.HasColumnName("register_date");

    b.Property<int>("Status")
.HasColumnType("int")
.HasColumnName("status");

    b.Property<DateTime>("UpdateDate")
.HasColumnType("datetime2")
.HasColumnName("update_date");

    b.Property<int>("UserId")
.HasColumnType("int")
.HasColumnName("user_id");

    b.HasKey("Id");

    b.HasIndex("CompanyId");

    b.HasIndex("UserId");

    b.ToTable("company_owners");
});

    modelBuilder.Entity("Scheduler.Models.Scheduling", b =>
{
    b.Property<int>("Id")
.ValueGeneratedOnAdd()
.HasColumnType("int")
.HasColumnName("id");

    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

    b.Property<int>("CompanyId")
.HasColumnType("int")
.HasColumnName("company_id");

    b.Property<int>("CustomerId")
.HasColumnType("int")
.HasColumnName("customer_id");

    b.Property<DateTime>("RegisterDate")
.HasColumnType("datetime2")
.HasColumnName("register_date");

    b.Property<DateTime>("ScheduledDate")
.HasColumnType("datetime2")
.HasColumnName("scheduled_date");

    b.Property<int>("Status")
.HasColumnType("int")
.HasColumnName("status");

    b.Property<DateTime>("UpdateDate")
.HasColumnType("datetime2")
.HasColumnName("update_date");

    b.HasKey("Id");

    b.HasIndex("CompanyId");

    b.HasIndex("CustomerId");

    b.ToTable("schedulings");
});

    modelBuilder.Entity("Scheduler.Models.ServicesOffered", b =>
{
    b.Property<int>("Id")
.ValueGeneratedOnAdd()
.HasColumnType("int")
.HasColumnName("id");

    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

    b.Property<int>("CompanyId")
.HasColumnType("int")
.HasColumnName("company_id");

    b.Property<DateTime>("Duration")
.HasColumnType("datetime2")
.HasColumnName("duration");

    b.Property<string>("Name")
.IsRequired()
.HasColumnType("nvarchar(max)")
.HasColumnName("name");

    b.Property<float>("Price")
.HasColumnType("real")
.HasColumnName("price");

    b.Property<DateTime>("RegisterDate")
.HasColumnType("datetime2")
.HasColumnName("register_date");

    b.Property<int>("Status")
.HasColumnType("int")
.HasColumnName("status");

    b.Property<DateTime>("UpdateDate")
.HasColumnType("datetime2")
.HasColumnName("update_date");

    b.HasKey("Id");

    b.HasIndex("CompanyId");

    b.ToTable("services_offered");
});

    modelBuilder.Entity("Scheduler.Models.User", b =>
{
    b.Property<int>("Id")
.ValueGeneratedOnAdd()
.HasColumnType("int")
.HasColumnName("id");

    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

    b.Property<DateTime>("BirthDate")
.HasColumnType("datetime2")
.HasColumnName("birth_date");

    b.Property<string>("Name")
.IsRequired()
.HasColumnType("nvarchar(max)")
.HasColumnName("name");

    b.Property<DateTime>("RegisterDate")
.HasColumnType("datetime2")
.HasColumnName("register_date");

    b.Property<int>("Status")
.HasColumnType("int")
.HasColumnName("status");

    b.Property<DateTime>("UpdateDate")
.HasColumnType("datetime2")
.HasColumnName("update_date");

    b.HasKey("Id");

    b.ToTable("users");
});

    modelBuilder.Entity("Scheduler.Models.CompanyOpeningHours", b =>
{
    b.HasOne("Scheduler.Models.Company", "Company")
.WithMany()
.HasForeignKey("CompanyId")
.OnDelete(DeleteBehavior.Cascade)
.IsRequired();

    b.Navigation("Company");
});

    modelBuilder.Entity("Scheduler.Models.CompanyOwners", b =>
{
    b.HasOne("Scheduler.Models.Company", "Company")
.WithMany()
.HasForeignKey("CompanyId")
.OnDelete(DeleteBehavior.Cascade)
.IsRequired();

    b.HasOne("Scheduler.Models.User", "User")
.WithMany("Companies")
.HasForeignKey("UserId")
.OnDelete(DeleteBehavior.Cascade)
.IsRequired();

    b.Navigation("Company");

    b.Navigation("User");
});

    modelBuilder.Entity("Scheduler.Models.Scheduling", b =>
{
    b.HasOne("Scheduler.Models.Company", "Company")
.WithMany()
.HasForeignKey("CompanyId")
.OnDelete(DeleteBehavior.Cascade)
.IsRequired();

    b.HasOne("Scheduler.Models.User", "Customer")
.WithMany()
.HasForeignKey("CustomerId")
.OnDelete(DeleteBehavior.Cascade)
.IsRequired();

    b.Navigation("Company");

    b.Navigation("Customer");
});

    modelBuilder.Entity("Scheduler.Models.ServicesOffered", b =>
{
    b.HasOne("Scheduler.Models.Company", "Company")
.WithMany("ServicesOffered")
.HasForeignKey("CompanyId")
.OnDelete(DeleteBehavior.Cascade)
.IsRequired();

    b.Navigation("Company");
});

    modelBuilder.Entity("Scheduler.Models.Company", b =>
{
    b.Navigation("ServicesOffered");
});

    modelBuilder.Entity("Scheduler.Models.User", b =>
{
    b.Navigation("Companies");
});
#pragma warning restore 612, 618
}
    }
}
