// <auto-generated />
using System;
using AppAgendamentos.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppAgendamentos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230316010321_Adding_New_Tables")]
    partial class Adding_New_Tables
    {
***REMOVED***/// <inheritdoc />
***REMOVED***protected override void BuildTargetModel(ModelBuilder modelBuilder)
***REMOVED***{
#pragma warning disable 612, 618
***REMOVED***    modelBuilder
***REMOVED******REMOVED***.HasAnnotation("ProductVersion", "7.0.3")
***REMOVED******REMOVED***.HasAnnotation("Relational:MaxIdentifierLength", 128);

***REMOVED***    SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

***REMOVED***    modelBuilder.Entity("AppAgendamentos.Models.Category", b =>
***REMOVED******REMOVED***{
***REMOVED******REMOVED***    b.Property<int>("Id")
***REMOVED******REMOVED******REMOVED***.ValueGeneratedOnAdd()
***REMOVED******REMOVED******REMOVED***.HasColumnType("int")
***REMOVED******REMOVED******REMOVED***.HasColumnName("id");

***REMOVED******REMOVED***    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

***REMOVED******REMOVED***    b.Property<string>("Name")
***REMOVED******REMOVED******REMOVED***.HasColumnType("nvarchar(max)")
***REMOVED******REMOVED******REMOVED***.HasColumnName("name");

***REMOVED******REMOVED***    b.Property<DateTime>("RegisterDate")
***REMOVED******REMOVED******REMOVED***.HasColumnType("datetime2")
***REMOVED******REMOVED******REMOVED***.HasColumnName("register_date");

***REMOVED******REMOVED***    b.Property<int>("Status")
***REMOVED******REMOVED******REMOVED***.HasColumnType("int")
***REMOVED******REMOVED******REMOVED***.HasColumnName("status");

***REMOVED******REMOVED***    b.Property<DateTime>("UpdateDate")
***REMOVED******REMOVED******REMOVED***.HasColumnType("datetime2")
***REMOVED******REMOVED******REMOVED***.HasColumnName("update_date");

***REMOVED******REMOVED***    b.HasKey("Id");

***REMOVED******REMOVED***    b.ToTable("categories");
***REMOVED******REMOVED***});

***REMOVED***    modelBuilder.Entity("AppAgendamentos.Models.Company", b =>
***REMOVED******REMOVED***{
***REMOVED******REMOVED***    b.Property<int>("Id")
***REMOVED******REMOVED******REMOVED***.ValueGeneratedOnAdd()
***REMOVED******REMOVED******REMOVED***.HasColumnType("int")
***REMOVED******REMOVED******REMOVED***.HasColumnName("id");

***REMOVED******REMOVED***    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

***REMOVED******REMOVED***    b.Property<string>("CNPJ")
***REMOVED******REMOVED******REMOVED***.HasColumnType("nvarchar(max)")
***REMOVED******REMOVED******REMOVED***.HasColumnName("c_n_p_j");

***REMOVED******REMOVED***    b.Property<string>("Description")
***REMOVED******REMOVED******REMOVED***.IsRequired()
***REMOVED******REMOVED******REMOVED***.HasColumnType("nvarchar(max)")
***REMOVED******REMOVED******REMOVED***.HasColumnName("description");

***REMOVED******REMOVED***    b.Property<string>("Name")
***REMOVED******REMOVED******REMOVED***.IsRequired()
***REMOVED******REMOVED******REMOVED***.HasColumnType("nvarchar(max)")
***REMOVED******REMOVED******REMOVED***.HasColumnName("name");

***REMOVED******REMOVED***    b.Property<DateTime>("RegisterDate")
***REMOVED******REMOVED******REMOVED***.HasColumnType("datetime2")
***REMOVED******REMOVED******REMOVED***.HasColumnName("register_date");

***REMOVED******REMOVED***    b.Property<int>("Status")
***REMOVED******REMOVED******REMOVED***.HasColumnType("int")
***REMOVED******REMOVED******REMOVED***.HasColumnName("status");

***REMOVED******REMOVED***    b.Property<DateTime>("UpdateDate")
***REMOVED******REMOVED******REMOVED***.HasColumnType("datetime2")
***REMOVED******REMOVED******REMOVED***.HasColumnName("update_date");

***REMOVED******REMOVED***    b.HasKey("Id");

***REMOVED******REMOVED***    b.ToTable("companies");
***REMOVED******REMOVED***});

***REMOVED***    modelBuilder.Entity("AppAgendamentos.Models.CompanyOwners", b =>
***REMOVED******REMOVED***{
***REMOVED******REMOVED***    b.Property<int>("Id")
***REMOVED******REMOVED******REMOVED***.ValueGeneratedOnAdd()
***REMOVED******REMOVED******REMOVED***.HasColumnType("int")
***REMOVED******REMOVED******REMOVED***.HasColumnName("id");

***REMOVED******REMOVED***    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

***REMOVED******REMOVED***    b.Property<int>("CompanyId")
***REMOVED******REMOVED******REMOVED***.HasColumnType("int")
***REMOVED******REMOVED******REMOVED***.HasColumnName("company_id");

***REMOVED******REMOVED***    b.Property<DateTime>("RegisterDate")
***REMOVED******REMOVED******REMOVED***.HasColumnType("datetime2")
***REMOVED******REMOVED******REMOVED***.HasColumnName("register_date");

***REMOVED******REMOVED***    b.Property<int>("Status")
***REMOVED******REMOVED******REMOVED***.HasColumnType("int")
***REMOVED******REMOVED******REMOVED***.HasColumnName("status");

***REMOVED******REMOVED***    b.Property<DateTime>("UpdateDate")
***REMOVED******REMOVED******REMOVED***.HasColumnType("datetime2")
***REMOVED******REMOVED******REMOVED***.HasColumnName("update_date");

***REMOVED******REMOVED***    b.Property<int>("UserId")
***REMOVED******REMOVED******REMOVED***.HasColumnType("int")
***REMOVED******REMOVED******REMOVED***.HasColumnName("user_id");

***REMOVED******REMOVED***    b.HasKey("Id");

***REMOVED******REMOVED***    b.HasIndex("CompanyId");

***REMOVED******REMOVED***    b.HasIndex("UserId");

***REMOVED******REMOVED***    b.ToTable("company_owners");
***REMOVED******REMOVED***});

***REMOVED***    modelBuilder.Entity("AppAgendamentos.Models.ServicesOffered", b =>
***REMOVED******REMOVED***{
***REMOVED******REMOVED***    b.Property<int>("Id")
***REMOVED******REMOVED******REMOVED***.ValueGeneratedOnAdd()
***REMOVED******REMOVED******REMOVED***.HasColumnType("int")
***REMOVED******REMOVED******REMOVED***.HasColumnName("id");

***REMOVED******REMOVED***    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

***REMOVED******REMOVED***    b.Property<int>("CompanyId")
***REMOVED******REMOVED******REMOVED***.HasColumnType("int")
***REMOVED******REMOVED******REMOVED***.HasColumnName("company_id");

***REMOVED******REMOVED***    b.Property<string>("Name")
***REMOVED******REMOVED******REMOVED***.IsRequired()
***REMOVED******REMOVED******REMOVED***.HasColumnType("nvarchar(max)")
***REMOVED******REMOVED******REMOVED***.HasColumnName("name");

***REMOVED******REMOVED***    b.Property<float>("Price")
***REMOVED******REMOVED******REMOVED***.HasColumnType("real")
***REMOVED******REMOVED******REMOVED***.HasColumnName("price");

***REMOVED******REMOVED***    b.Property<DateTime>("RegisterDate")
***REMOVED******REMOVED******REMOVED***.HasColumnType("datetime2")
***REMOVED******REMOVED******REMOVED***.HasColumnName("register_date");

***REMOVED******REMOVED***    b.Property<int>("Status")
***REMOVED******REMOVED******REMOVED***.HasColumnType("int")
***REMOVED******REMOVED******REMOVED***.HasColumnName("status");

***REMOVED******REMOVED***    b.Property<DateTime>("UpdateDate")
***REMOVED******REMOVED******REMOVED***.HasColumnType("datetime2")
***REMOVED******REMOVED******REMOVED***.HasColumnName("update_date");

***REMOVED******REMOVED***    b.HasKey("Id");

***REMOVED******REMOVED***    b.ToTable("services_offered");
***REMOVED******REMOVED***});

***REMOVED***    modelBuilder.Entity("AppAgendamentos.Models.User", b =>
***REMOVED******REMOVED***{
***REMOVED******REMOVED***    b.Property<int>("Id")
***REMOVED******REMOVED******REMOVED***.ValueGeneratedOnAdd()
***REMOVED******REMOVED******REMOVED***.HasColumnType("int")
***REMOVED******REMOVED******REMOVED***.HasColumnName("id");

***REMOVED******REMOVED***    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

***REMOVED******REMOVED***    b.Property<DateTime>("BirthDate")
***REMOVED******REMOVED******REMOVED***.HasColumnType("datetime2")
***REMOVED******REMOVED******REMOVED***.HasColumnName("birth_date");

***REMOVED******REMOVED***    b.Property<string>("Name")
***REMOVED******REMOVED******REMOVED***.IsRequired()
***REMOVED******REMOVED******REMOVED***.HasColumnType("nvarchar(max)")
***REMOVED******REMOVED******REMOVED***.HasColumnName("name");

***REMOVED******REMOVED***    b.Property<DateTime>("RegisterDate")
***REMOVED******REMOVED******REMOVED***.HasColumnType("datetime2")
***REMOVED******REMOVED******REMOVED***.HasColumnName("register_date");

***REMOVED******REMOVED***    b.Property<int>("Status")
***REMOVED******REMOVED******REMOVED***.HasColumnType("int")
***REMOVED******REMOVED******REMOVED***.HasColumnName("status");

***REMOVED******REMOVED***    b.Property<DateTime>("UpdateDate")
***REMOVED******REMOVED******REMOVED***.HasColumnType("datetime2")
***REMOVED******REMOVED******REMOVED***.HasColumnName("update_date");

***REMOVED******REMOVED***    b.HasKey("Id");

***REMOVED******REMOVED***    b.ToTable("users");
***REMOVED******REMOVED***});

***REMOVED***    modelBuilder.Entity("AppAgendamentos.Models.CompanyOwners", b =>
***REMOVED******REMOVED***{
***REMOVED******REMOVED***    b.HasOne("AppAgendamentos.Models.Company", "Company")
***REMOVED******REMOVED******REMOVED***.WithMany()
***REMOVED******REMOVED******REMOVED***.HasForeignKey("CompanyId")
***REMOVED******REMOVED******REMOVED***.OnDelete(DeleteBehavior.Cascade)
***REMOVED******REMOVED******REMOVED***.IsRequired();

***REMOVED******REMOVED***    b.HasOne("AppAgendamentos.Models.User", "User")
***REMOVED******REMOVED******REMOVED***.WithMany("Companies")
***REMOVED******REMOVED******REMOVED***.HasForeignKey("UserId")
***REMOVED******REMOVED******REMOVED***.OnDelete(DeleteBehavior.Cascade)
***REMOVED******REMOVED******REMOVED***.IsRequired();

***REMOVED******REMOVED***    b.Navigation("Company");

***REMOVED******REMOVED***    b.Navigation("User");
***REMOVED******REMOVED***});

***REMOVED***    modelBuilder.Entity("AppAgendamentos.Models.User", b =>
***REMOVED******REMOVED***{
***REMOVED******REMOVED***    b.Navigation("Companies");
***REMOVED******REMOVED***});
#pragma warning restore 612, 618
***REMOVED***}
    }
}
