using Microsoft.AspNetCore.Identity;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppAgendamentos.Models;
[Table("users")]
public class ApplicationUser : IdentityUser<int>
{
    [Required]
    public DateTime BirthDate { get; set; }
    public string CPF { get; set; }
    public string Password { get; set; }
    public string ConfirmPassword { get; set; }
    public ICollection<CompanyOwners> Companies { get; set; }
    [Required]
    public override string UserName { get; set; }
    [Required]
    public override string Email { get; set; }
    public int? CityId { get; set; }
    public City City { get; set; }
    public string Address { get; set; }
    public string AddressNumber { get; set; }
    public string PostalCode { get; set; }
    public string ImageUrl { get; set; }
    public bool AutoGeneratedImage { get; set; }
    public string ImagePrompt { get; set; }
    public string ImageBase64 { get; set; }

    public IList<Scheduling> Schedulings { get; set; }
}