using Microsoft.AspNetCore.Identity;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppAgendamentos.Models;
public class ApplicationUser : IdentityUser<int>
{
    [Required]
    public DateTime BirthDate { get; set; }
    public string CPF { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public int? CityId { get; set; }
    public City City { get; set; }

    public bool AutoGeneratedImage { get; set; }
    public string ImageUrl { get; set; }
    public string ImagePrompt { get; set; }
    [NotMapped]
    public string ImageBase64 { get; set; }


    public string Address { get; set; }
    public string AddressNumber { get; set; }
    public string PostalCode { get; set; }

    public IList<Scheduling> Schedulings { get; set; }
    public IList<CompanyOwners> UserCompanies { get; set; }
    [NotMapped]
    public IList<Company> Companies { get; set; }
}